### ISSUE TITLE
Build Base Swerve Drive

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2023-Charged-Up#1]
We want to start our Swerve Drive over, making sure to validate that all values (angles, distances) are reported accurately and in the right orientations we want.

(This does not include angle optimizations and more advanced features)

**Comment by aqhoang2005** [comment]
Basically done, wait for actual robot (have basic code working)

**Comment by jnallard** [comment]
Tested with #45

**Comment by huyha23** [comment]
This is done.
