### ISSUE TITLE
Presentation on Commands in WPILib

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2023-Charged-Up#33]
Give a presentation on the Command System in WPILib and how we use it.

Detail (at minimum) the following:
- [x] What is a Command?
- [x] What is the lifecycle of a command?
- [x] What is the command scheduler and what does it do?
- [x] What are the subsystems? And how do they affect the commands when added as requirements for commands?
- [x] What types of commands are there?
- [x] #53
- [x] Can we group commands together? In sequence? In Parallel?
- [x] How do we use commands? In teleop? In Auto?
  - [x] How do Buttons/Triggers work with the command scheduler?
- [x] Whatever else is cool about them

**Comment by aqhoang2005** [comment]
https://docs.google.com/presentation/d/1yaVRmMJm4nKBC7HUOOfG3NtA4s6UWQcFQPCw36Wim3s/edit?usp=sharing

Slideshow link if anyone wants to review it

**Comment by aqhoang2005** [comment]
All slides are completed, covering the issues listed above. The link for the slideshow is here: https://docs.google.com/presentation/d/1yaVRmMJm4nKBC7HUOOfG3NtA4s6UWQcFQPCw36Wim3s/edit?usp=sharing

Comment mode is on if changes need to be suggested.
