### ISSUE TITLE
Do research on how we controlled the robot's arm in 2019

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2023-Charged-Up#40]
In 2019, we did an arm similar to the one we are building this year.

Look into the code and look at pictures of our robot found online or in the programming room, and document how we controlled the robot:
https://github.com/Manchester-Central/2019-Deep-Space/tree/master/2019%20Deep%20Space/src/main/java/frc

**Comment by huyha23** [comment]
This is the note that write our research in.
https://docs.google.com/document/d/1ow2lJAeOUQqRGKbonaUx56_BgUCMhr636StlxjDxioQ/edit?usp=sharing

**Comment by jnallard** [comment]
Thanks @AratosUnderscore and @huyha23!
