### ISSUE TITLE
Only use `MaxRobotSpeed_mps` and `MaxRobotRotation_radps` in `SwerveDrive.move(speeds)`

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2023-Charged-Up#47]
Right now, we have to specify the max speeds in every command where we convert joysticks values (-1.00, 1.00) to robot speeds. 
Rather than doing this logic in every command, we can use (-1.00, 1.00) throughout the code, except in the spot where we actually tell the swerve modules to move, `SwerveDrive.move()`.
So, in the command, to go full x speed, we will say 1.00 for x speed in the command, but in move(), we will translate that to `1.00 * SwerveConstants.MaxRobotSpeed_mps`

-------------------

We want to keep all of the swerve drive commands to reference speeds (meters per second and radians per second) in a percent value (`-1,00` to `+1.00`). 

So we should do the following:
- [x] Remove current references, such as in `DriverRelativeDrive.execute()`, where we multiply the jostick values by the max constants
- [x] Update SwerveDrive.move() to create a new version of ChassisSpeeds with the percent values multiplied by the max speeds
  - [x] Before we do this, we want to clamp the percent values, to guarantee they are between `-1,00` and `+1.00` (see `MathUtil.clamp`)
- [x] Pass the new scaled speeds to `m_kinematics.toSwerveModuleStates`

Additional. we might be a good time to do this improvement:
https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.html#desaturateWheelSpeeds(edu.wpi.first.math.kinematics.SwerveModuleState%5B%5D,double)

**Comment by huyha23** [comment]
Desaturate Wheel Speed: #
